[[redirects]]
  from = "http://blog.codeforscience.org/*"
  to = "https://css-new.netlify.com/blog/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://blog.codeforscience.org/*"
  to = "https://css-new.netlify.com/blog/:splat"
  status = 301
  force = true 
  
[[redirects]]
  from = "/blog/*"
  to = "https://css-new.netlify.com/blog/:splat"
  status = 200
  force = true 
  headers = {X-Forwarded-Host = "css-new.netlify.com"}
