backend:
  name: git-gateway
  branch: live

publish_mode: editorial_workflow

media_folder: src/public/img
public_folder: /img

collections:
  # Globals
  - name: content
    label: Content
    files:
      - label: 'Globals'
        name: 'globals'
        file: 'src/site/_data/globals.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Tagline', name: 'tagline', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Logo', name: 'logo', widget: 'image' }
          - { label: 'Background', name: 'background', widget: 'image' }
          - { label: 'Footer Text', name: 'footer', widget: 'string' }
          - label: 'Programs'
            name: 'programs'
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - { label: 'Description', name: 'description', widget: 'markdown' }
          - label: 'Contact'
            name: 'contact'
            widget: 'object'
            fields:
              - { label: 'Twitter', name: 'twitter', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
          - label: "Footer Navigation"
            name: footerNav
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - label: Links
                name: links
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: URL, name: url, widget: string}
                  - {label: 'External', name: 'external', widget: 'boolean', hint: 'Set to external to handle external links without using the router.', required: false, default: false}
      # People Page
      - label: 'People Page'
        name: 'People'
        file: 'src/site/_data/pages/people.json'
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - label: 'Group'
            name: 'group'
            widget: 'list'
            fields:
              - {label: 'Group Name', name: name, widget: string}
              - {label: 'Description', name: 'description', widget: 'markdown', buttons: ['link'], required: false}
              - label: "People"
                name: "people"
                widget: "relation"
                collection: "people"
                searchFields: ["name"]
                multiple: true
                valueField: "name"
                displayFields: ["name"]


  - label: 'Collection: People'
    label_singular: 'Person'
    name: 'people'
    identifier_field: 'name'
    folder: 'src/site/_data/people'
    create: true
    format: 'json'
    slug: "{{name}}"
    fields:
      - {label: 'Name', name: 'name', widget: 'string', hint: 'First and last name; required.', required: true}
      - {label: 'Title', name: 'title', widget: 'string', required: false}
      - {label: 'Bio', name: 'bio', widget: 'markdown', buttons: ['link'], required: false}
      - {label: 'Image', name: 'image', widget: 'image', required: false }
      - {label: 'Image Alt Text', name: 'imageAltText', widget: 'string', required: false, hint: "Briefly describe the image; this will be read by screen readers." }
      - {label: 'Website', name: 'website', widget: 'string', required: false, hint: 'If this is present, both image and name will link there.'}


  - label: 'Collection: Jobs'
    label_singular: 'Job'
    name: 'jobs'
    folder: 'src/site/_data/jobs'
    create: true
    slug: "{{year}}-{{month}}_{{slug}}"
    format: 'json'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Short Description', name: 'description', widget: 'markdown' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Use Airtable Form', name: 'useForm', widget: 'boolean', default: false }
